fix clang-cl compilation
Fixes:

error: invalid bitwise operation between different enumeration types

Signed-off-by: Rosen Penev <rosenp@gmail.com>
(cherry picked from commit 84eefdae2e4fcb588a322b91fd732e825e788ea6)